#include "t_device_init.h"
#include "taud.h"

/*===========================================================================*/
/* Assign ISR later */
/*===========================================================================*/
void (*INTTAUD0I0_ISR)(void) = R_NULL;
void (*INTTAUJ0I1_ISR)(void) = R_NULL;

/*===========================================================================*/
/* Interrupts */
/*===========================================================================*/
/*****************************************************************************
** Function:    INTTAUJ0I1
** Description: Interrupt generated by channel 1 of TAUD0. In case of interrupt,
**              ISR function assigned to pointer R_INTTAUD0I1_ISR is called.
** Parameter:   None
** Return:      None
******************************************************************************/

#pragma interrupt INTTAUD0I0(enable=manual)
void INTTAUD0I0(void){
    if(INTTAUD0I0_ISR != R_NULL)
    {
        INTTAUD0I0_ISR();
    }
}

#pragma interrupt INTTAUJ0I1(enable=manual)
void INTTAUJ0I1(void)
{
    if(INTTAUJ0I1_ISR != R_NULL)
    {
        INTTAUJ0I1_ISR();
    }
}
/*===========================================================================*/
/* Functions */
/*===========================================================================*/
/*****************************************************************************
** Function:    R_TAUD0_AssignChannel1ISR
** Description: Assigns a service routine to the function which is called inside 
**              the channel 1 interrupt.
** Parameter:   ISR_Ptr - Function pointer
** Return:      None
******************************************************************************/
void TAUD0_AssignChannel0ISR(void ISR_Ptr(void))
{
    INTTAUD0I0_ISR = ISR_Ptr;
}
/*****************************************************************************
** Function:    R_TAUD0_CDR_Update
** Description: Update Channel Data Register
** Parameter:   CDR_val - new CDR Value
** Return:      None
******************************************************************************/
void TAUD0_CDR_Update(uint16_t CDR_val){
	TAUD0CDR0 = CDR_val;
        TAUD0RDT = TAUD0C0;	
}
/*****************************************************************************
** Function:    R_TAUD0_CK0_Prescaler
** Description: Sets the Prescaler of TAUD0 Clock 0.
** Parameter:   Prescaler - CK0 = TAUD0CLK/(2^Prescaler)
** Return:      None
******************************************************************************/
void TAUD_CK0_Prescaler(uint8_t Prescaler){
	TAUD0TPS &= 0xfff0;
	Prescaler &= 0x0f;
	TAUD0TPS |= Prescaler;
}

/*****************************************************************************
** Function:    TAUD0_Channel0_Init
** Description: Configures TAUD0 Channel 0 to Interval Timer Mode.
** Parameter:   None
** Return:      None
******************************************************************************/
void TAUD0_Channel0_Init(void)
{
  TAUD0CMOR0 = 0x0000u;            /* Select CK0 */
  TAUD0CMUR0 = 0x00u;              /* Interval timer mode */
  TAUD0CDR0 = 0x1D4Bu;
}
/*****************************************************************************
** Function:    TAUD0_Channel_Start
** Description: 
** Parameter:   None
** Return:      None
******************************************************************************/
void TAUD0_Channel_Start()
{
  TAUD0TS = 0x01; 
}

/*****************************************************************************
** Function:    TAUJ0_Channel_Stop
** Description: Sets the Stop Trigger of the corresponding TAUJ0 Channel.
** Parameter:   
** Return:      None
******************************************************************************/
void TAUD0_Channel_Stop()
{
  TAUD0TT = 0x01;
}

uint16_t get_counter_value(){
	uint16_t value = TAUD0CNT0;
	return value;
}

uint16_t get_status_reg(){
	uint16_t value = TAUD0CSR0;
	return value;

}

/*****************************************************************************
** Function:    R_TAUJ0_CK0_Prescaler
** Description: Sets the Prescaler of TAUJ0 Clock 0.
** Parameter:   Prescaler - CK0 = TAUJ0CLK/(2^Prescaler)
** Return:      None
******************************************************************************/

void TAUJ0_CK0_Prescaler(uint8_t Prescaler)
{
  TAUJ0TPS &= 0xfff0;
  Prescaler &= 0x0f;
  TAUJ0TPS |= Prescaler;
}

/*****************************************************************************
** Function:    R_TAUJ0_Channel1_Init
** Description: 
** Parameter:   None
** Return:      None
******************************************************************************/
void TAUJ0_Channel1_Init(void)
{  
  TAUJ0CMOR1 = 0x0000u;         /* Select CK0 */
  TAUJ0CMUR1 = 0x00u;           /* Interval timer mode */
  TAUJ0CDR1 = 0xFFFFu;
//  TAUJ0RDT  = 0x02;
}
/*****************************************************************************
** Function:    R_TAUJ0_AssignChannel1ISR
** Description: Assigns a service routine to the function which is called inside 
**              the channel 1 interrupt.
** Parameter:   ISR_Ptr - Function pointer
** Return:      None
******************************************************************************/
void TAUJ0_AssignChannel1ISR(void ISR_Ptr(void))
{
    INTTAUJ0I1_ISR = ISR_Ptr;
}
/*****************************************************************************
** Function:    R_TAUJ0_Channel_Start
** Description: 
** Parameter:   None
** Return:      None
******************************************************************************/
void TAUJ0_Channel_Start(uint16_t TAUJ0_Channel)
{
  TAUJ0TS = TAUJ0_Channel; 
}

/*****************************************************************************
** Function:    R_TAUJ0_Channel_Stop
** Description: Sets the Stop Trigger of the corresponding TAUJ0 Channel.
** Parameter:   
** Return:      None
******************************************************************************/
void TAUJ0_Channel_Stop(uint16_t TAUJ0_Channel)
{
  TAUJ0TT = TAUJ0_Channel;
}

